name: kenreyeslao
favicon: null
layout_spectrum: 0.41553841764107347
typography_spectrum: 0.18971129972487688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4539982902351767
  lightness: 0.8989782098215073
  saturation: 0.033845428843051195
  rhythmicContrast: 0.6819647753145546
purpose: []
